
service: test2
provider:
      name: aws
      runtime: nodejs12.x
      iamRoleStatements:
              - Effect: Allow
                Action:
                  - dynamodb:DescribeTable
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                Resource:
                   Fn::Join:
                     - ""
                     - - "arn:aws:dynamodb:*:*:table/"
                       - Ref: UserGqlDynamoDbTable
                       - Ref: OrderGqlDynamoDbTable
                       - Ref: TaskGqlDynamoDbTable

functions:
      queryUsers:
        handler: handler/userhandler.queryUsers
        events:
        - http:
            path: users
            method: post
            cors: true
        environment:
          TABLE_NAME: test00_users
      queryOrders:
        handler: handler/orderhandler.queryOrders
        events:
        - http:
            path: orders
            method: post
            cors: true
        environment:
          TABLE_NAME: test00_orders
          SUB_TABLE_NAME : test00_users
      queryTasks:
        handler: handler/taskhandler.queryTasks
        events:
        - http:
            path: tasks
            method: post
            cors: true
        environment:
          TABLE_NAME: test00_tasks
       
          

resources:
      Resources:
        UserGqlDynamoDbTable:
          Type: AWS::DynamoDB::Table
          Properties:
            TableName: test00_users
            AttributeDefinitions:
              - AttributeName: id
                AttributeType: S
              - AttributeName: createdAt
                AttributeType: S
              - AttributeName: status
                AttributeType: S
              - AttributeName: posit
                AttributeType: S
              - AttributeName: username
                AttributeType: S
            KeySchema:
              - AttributeName: id
                KeyType: HASH
              - AttributeName: createdAt
                KeyType: RANGE
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
            LocalSecondaryIndexes:
              - IndexName: username_index
                KeySchema:
                - AttributeName: id
                  KeyType: HASH
                - AttributeName: username
                  KeyType: RANGE
              - IndexName: status_index
                KeySchema:
                - AttributeName: id
                  KeyType: HASH
                - AttributeName: status
                  KeyType: RANGE
              - IndexName: posit_index
                KeySchema:
                - AttributeName: id
                  KeyType: HASH
                - AttributeName: posit
                  KeyType: RANGE  
            ProjectionType: ALL
        OrderGqlDynamoDbTable:
          Type: AWS::DynamoDB::Table
          Properties:
            TableName: test00_orders
            AttributeDefinitions:
              - AttributeName: id
                AttributeType: S
              - AttributeName: createdAt
                AttributeType: S
              - AttributeName: username
                AttributeType: S
              - AttributeName: menu
                AttributeType: S
              - AttributeName: hi
                AttributeType: S
            KeySchema:
              - AttributeName: id
                KeyType: HASH
              - AttributeName: createdAt
                KeyType: RANGE
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
            LocalSecondaryIndexes:
              - IndexName: username_index
                KeySchema:
                - AttributeName: id
                  KeyType: HASH
                - AttributeName: username
                  KeyType: RANGE
              - IndexName: menu_index
                KeySchema:
                - AttributeName: id
                  KeyType: HASH
                - AttributeName: menu
                  KeyType: RANGE
              - IndexName: hi_index
                KeySchema:
                - AttributeName: id
                  KeyType: HASH
                - AttributeName: hi
                  KeyType: RANGE  
            ProjectionType: ALL
        TaskGqlDynamoDbTable:
          Type: AWS::DynamoDB::Table
          Properties:
            TableName: test00_tasks
            AttributeDefinitions:
              - AttributeName: id
                AttributeType: S
            KeySchema:
              - AttributeName: id
                KeyType: HASH
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
       
plugins:
  - serverless-offline